name: 'Argus - AI Code Guardian'
description: 'A Serverless AI Security Engineer that blocks bad code using Groq.'
author: 'Mahesh Dindur'
branding:
  icon: 'shield'  
  color: 'purple'

inputs:
  groq_api_key:
    description: 'Your Groq API Key'
    required: true
  groq_model:
    description: 'Groq model used for PR review'
    required: false
    default: 'llama-3.1-8b-instant'
  github_token:
    description: 'The GitHub Token (automatically provided)'
    required: true
    default: ${{ github.token }}

runs:
  using: 'composite'
  steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      shell: bash
      run: |
        pip install groq requests

    - name: Run Argus Reviewer
      shell: bash
      env:
        GROQ_API_KEY: ${{ inputs.groq_api_key }}
        GROQ_MODEL: ${{ inputs.groq_model }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: python "$GITHUB_ACTION_PATH/scripts/reviewer.py"
